version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: daily-quote

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: node:20-alpine3.18
    restart: always
    working_dir: /usr/src/app
    env_file:
       - ./.env
    depends_on:
      - db
    ports:
      - 9001:9001
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev